module.exports = {
  'secret': 'welovetheworldlikeamotherlovesherson',
  'database': 'doc_store',
  'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInVzZXJuYW1lIjoiVG9tVG9tIiwiZmlyc3RuYW1lIjoiVG9tbXkiLCJsYXN0bmFtZSI6IkhpbEZpZ2VyIiwiZW1haWwiOiJ0b21AZ20uY29tIiwicGFzc3dvcmQiOiJVMkZzZEdWa1gxK3U4aUVOcnVUNnkzQmVnUVhKVDhGODlWcWh0bC8yNGtFPSIsInVwZGF0ZWRBdCI6IjIwMTYtMTAtMzBUMTk6Mzg6NTYuNTM5WiIsImNyZWF0ZWRBdCI6IjIwMTYtMTAtMzBUMTk6Mzg6NTYuNTM5WiIsIlJvbGVJZCI6bnVsbCwiaWF0IjoxNDc3ODU2MzM2LCJleHAiOjE0ODMwNDAzMzZ9.Z1yXySBIhyaLgjeAvnmmWfAyeWXpsq4Va7fkdqYgx6s'
};
